services:
    web:
        image: gerrur/pethome-backend:1.0
        ports: 
            - "8080:8080"
        depends_on:
            - postgres
            - minio
            - seq
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
    postgres:
        container_name: pet_home_postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: pet_home
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    seq:
        image: datalust/seq:latest
        container_name: seq
        restart: always
        environment: 
            - ACCEPT_EULA=Y
        ports: 
            - "5341:5341"
            - "8081:80"
    minio:
        container_name: minio
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
        command: server --console-address ":9001" /data
        restart: always        
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web 
        restart: always

volumes:
    postgres_data: 
    minio_data: 