// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHome.VolunteerRequests.Infrastructure.DbContexts;

#nullable disable

namespace PetHome.VolunteerRequests.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHome.VolunteerRequests.Domain.VolunteerRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<Guid>("DisscusionId")
                        .HasColumnType("uuid")
                        .HasColumnName("disscusionId_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("CreatedAt", "PetHome.VolunteerRequests.Domain.VolunteerRequest.CreatedAt#DateValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RejectionComment", "PetHome.VolunteerRequests.Domain.VolunteerRequest.RejectionComment#Comment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("reject_comment");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("VolunteerInfo", "PetHome.VolunteerRequests.Domain.VolunteerRequest.VolunteerInfo#VolunteerInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Description", "PetHome.VolunteerRequests.Domain.VolunteerRequest.VolunteerInfo#VolunteerInfo.Description#DescriptionValueObject", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("description");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Email", "PetHome.VolunteerRequests.Domain.VolunteerRequest.VolunteerInfo#VolunteerInfo.Email#Email", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("EmailValue")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("email");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("FullName", "PetHome.VolunteerRequests.Domain.VolunteerRequest.VolunteerInfo#VolunteerInfo.FullName#FullName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("first_name");

                                    b2.Property<string>("SecondName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("second_name");

                                    b2.Property<string>("Surname")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("surname");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Phone", "PetHome.VolunteerRequests.Domain.VolunteerRequest.VolunteerInfo#VolunteerInfo.Phone#Phone", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("PhoneNumber")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("phone");
                                });
                        });

                    b.HasKey("RequestId")
                        .HasName("pk_volunteer_requests");

                    b.ToTable("volunteer_requests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
