// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHome.VolunteerRequests.Infrastructure.DbContexts;

#nullable disable

namespace PetHome.VolunteerRequests.Infrastructure.Migrations.ReadDb
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20250317162603_initial_read")]
    partial class initial_read
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHome.Shared.Core.Dtos.VolunteerRequestDto", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisscusionId")
                        .HasColumnType("uuid")
                        .HasColumnName("disscusion_id");

                    b.Property<string>("RejectionComment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rejection_comment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("VolunteerInfo", "PetHome.Shared.Core.Dtos.VolunteerRequestDto.VolunteerInfo#VolunteerInfoDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("volunteer_info_description");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("volunteer_info_email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("volunteer_info_phone");

                            b1.ComplexProperty<Dictionary<string, object>>("FullName", "PetHome.Shared.Core.Dtos.VolunteerRequestDto.VolunteerInfo#VolunteerInfoDto.FullName#FullNameDto", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("volunteer_info_full_name_first_name");

                                    b2.Property<string>("SecondName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("volunteer_info_full_name_second_name");

                                    b2.Property<string>("Surname")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("volunteer_info_full_name_surname");
                                });
                        });

                    b.HasKey("RequestId")
                        .HasName("pk_volunteer_requests");

                    b.ToTable("volunteer_requests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
